### ISSUE TITLE
试了一下没有效果

### ISSUE THREAD

**Issue by BlademasterQAQ** [hujingnb/markdownImage#2]
程序输出正常，但是输出的结果和输入是一样的，怀疑是markdown的语法更新了
目前的markdown图片表达式：
不修改参数时：`![image](C:\Users\xxx.png)`
修改参数时：`<img src="C:\Users\xxx.png" alt="xxx" style="zoom: 67%;" />`

**Comment by hujingnb** [comment]
暂时还不支持修改参数后得img标签形式

**Comment by hujingnb** [comment]
已经对 img 标签进行支持了

**Comment by hujingnb** [comment]
增加对 img 标签的支持
