### ISSUE TITLE
请问大佬为什么转成picgo+链接的模式了，这种方法不好吗

### ISSUE THREAD

**Issue by cvster** [hujingnb/markdownImage#4]
如题

**Comment by hujingnb** [comment]
主要原因有: 
1. 使用图片链接的形式, 文件体积较小, 查看比较方便. 
2. PickGo + typore 实现图片插入直接上传, 无需在完成之后在用脚本处理一遍, 比较省心

直接转图片base64的方式, 我觉的更多的好处在于不用怕图片服务器突然倒了, 图片找不到了. 

不过我使用了阿里云的oss进行内容存储, 且使用自己的cdn域名访问图片, 即使哪一天阿里云倒了, 我将oss的图片挪到其他厂商, 改下cdn源即可.
