### ISSUE TITLE
”因本人改为使用: typore+PicGo+oss 进行文章的图片管理“，CSDN来的，博主用的阿里云对象存储？（我菜鸟没咋问过issue，见谅）

### ISSUE THREAD

**Issue by romancekami** [hujingnb/markdownImage#5]

**Comment by romancekami** [comment]
另外问下我看了一下readme文档，好像说是转换电脑上所有md文件中的图片，请问下它能指定转换某个md文件中的图片吗（之前只用python打过hello world，不知道怎么修改代码...）？

**Comment by novakho** [comment]
能转换指定路径的文档，但是无法对图片内图片进行压缩，我已经配了tinyPNG的API key了，还是不行，感觉是少参数，求大神指点。

**Comment by hujingnb** [comment]
> _No description provided._

抱歉, 刚看到. 我确实是使用阿里云的 oss, 不过使用其他服务商提供的也是一样的, 在 `picGo`改下配置, 使用方式上没什么区别

**Comment by hujingnb** [comment]
> 另外问下我看了一下readme文档，好像说是转换电脑上所有md文件中的图片，请问下它能指定转换某个md文件中的图片吗（之前只用python打过hello world，不知道怎么修改代码...）？

并不是转换本地所有`md`文件, 每次运行只能转换一个特定的文件. 可以运行命令`python main.py -h` 来查看所有可接收的参数

**Comment by hujingnb** [comment]
> 能转换指定路径的文档，但是无法对图片内图片进行压缩，我已经配了tinyPNG的API key了，还是不行，感觉是少参数，求大神指点。

具体原因可调试一下, 在`ImageCompress.py:38`这一行, 图片压缩报错时, 现在的处理方式将错误忽略了, 你可以试着打印一下, 看是否报错了

**Comment by hujingnb** [comment]
> 能转换指定路径的文档，但是无法对图片内图片进行压缩，我已经配了tinyPNG的API key了，还是不行，感觉是少参数，求大神指点。

我刚刚添加了`--debug`参数, 可在图片压缩失败的时候将错误打印到控制台, 你可以试一下
